spring.application.name=06_Spring_JPA
spring.datasource.url=jdbc:h2:mem:kumar
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=kumar
spring.datasource.password=kumar

spring.jpa.show-sql=true
